spring.application.name=backend-Isildur-gondor-chic
spring.datasource.url=jdbc:postgresql://localhost:5432/gondor-chic?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver
spring.sql.init.encoding=UTF-8

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true


server.port=8081
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
